# Generated by Django 3.0.5 on 2020-12-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['thought_date']},
        ),
        migrations.RemoveField(
            model_name='thought',
            name='thought_id',
        ),
    ]
