# Generated by Django 3.0.5 on 2020-12-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0002_auto_20201230_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={},
        ),
    ]
